### ISSUE TITLE
Unsuccessful read: A timeout occurred before the Terminator was reached.

### ISSUE THREAD

**Issue by AmirHosseinAlikhahMishamandani** [SayanSeth/MPU-6050-Arduino-and-Matlab#1]
Hi, thanks for all your efforts,

I was wondering why am I getting this error, the Arduino is connected to the COM3 port and it is fully functioning. but when I run your code, I face this error ...

Warning: Unsuccessful read: A timeout occurred before the Terminator was reached.
'serial' unable to read all requested data. For more information on possible reasons, see Serial Read Warnings. 
MWProtocolWarning: Unsuccessful read: A timeout occurred before the Terminator was reached.
'serial' unable to read any data. For more information on possible reasons, see Serial Read Warnings. 
Index exceeds array bounds.

Error in Gyroscope_Visualization (line 52)
    if ~strcmp(sms(1:3),'ypr')

thanks in advance for your help!

**Comment by 46114146029** [comment]
Hello amir
The problem is your port used by another apps. You can try to plug out the port then plug in again. Another alternative is you can restart your PC

I hope it can help you

**Comment by AmirHosseinAlikhahMishamandani** [comment]
Hi, 

thanks for your reply. In my case, I downloaded and installed the "Instrument Control Toolbox Support Package for National Instruments VISA and ICP Interfaces" from MATLAB Add-ons and resolved my connection problem. 

Regards,
Amir
